

common: &common
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password:
  pool: 5

development:
  <<: *common
  database: drinkhere_development

test:
  <<: *common
  database: drinkhere_test

production:
  <<: *common
  database: drinkhere_production
  username: postgres
  password: postgres
